# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.16

ARG CSI_PARAMS=csi_params

RUN git clone https://github.com/kubernetes-csi/csi-test /usr/local/go/src/github.com/kubernetes-csi/csi-test
RUN make -C /usr/local/go/src/github.com/kubernetes-csi/csi-test

COPY ./scripts/csi_test /usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver

RUN groupadd -g 9999 appuser && \
    useradd -r -u 9999 -g appuser appuser
RUN chown -R appuser:appuser /usr/local/go/src/github.com/kubernetes-csi/csi-test

USER appuser
WORKDIR /usr/local/go/src/github.com/kubernetes-csi/csi-test

ENV JUNIT_OUTPUT="/tmp/test_results/out_client.xml"
ENV SECRET_FILE="/usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver/csi_secrets"
ENV PARAM_FILE="/usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver/${CSI_PARAMS}"
ENV ENDPOINT="/tmp/k8s_dir/nodecsi"
ENV ENDPOINT_CONTROLLER="/tmp/k8s_dir/f"
ENV TESTS_TO_SKIP_FILE="/usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver/csi_tests_to_skip"

ENTRYPOINT ["/usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver/entrypoint-csi-tests.sh"]
