# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM registry.access.redhat.com/ubi8/python-38:1-75.1638364053 as builder
USER root
RUN if [[ "$(uname -m)" != "x86"* ]]; then yum install -y rust-toolset; fi
USER default
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
RUN pip3 install --ignore-installed --default-timeout=100 --upgrade pip==21.2.4
WORKDIR /tmp
COPY controllers/servers/csi/requirements.txt .
# avoid default boringssl lib, since it does not support z systems
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True
RUN pip3 install -r ./requirements.txt

USER root
COPY controllers/scripts/csi_general .
RUN ./csi_pb2.sh
RUN pip3 install .


FROM registry.access.redhat.com/ubi8/python-38:1-100
MAINTAINER IBM Storage

ARG VERSION=1.10.0
ARG BUILD_NUMBER=0

###Required Labels
LABEL name="IBM block storage CSI driver controller" \
      vendor="IBM" \
      version=$VERSION \
      release=$BUILD_NUMBER \
      summary="The controller component of the IBM block storage CSI driver" \
      description="The IBM block storage CSI driver enables container orchestrators, such as Kubernetes and OpenShift, to manage the life-cycle of persistent storage." \
      io.k8s.display-name="IBM block storage CSI driver controller" \
      io.k8s.description="The IBM block storage CSI driver enables container orchestrators, such as Kubernetes and OpenShift, to manage the life-cycle of persistent storage." \
      io.openshift.tags=ibm,csi,ibm-block-csi-driver,ibm-block-csi-node

COPY --from=builder /opt/app-root /opt/app-root
COPY ./common /driver/common
COPY ./controllers/ /driver/controllers/
COPY ./LICENSE /licenses/
COPY ./NOTICES /licenses/

WORKDIR /driver
ENV PYTHONPATH=/driver

# Note: UBI runs with app-user by default.

ENTRYPOINT ["/driver/controllers/scripts/entrypoint.sh"]
