# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build stage
FROM golang:1.13 as builder

WORKDIR /go/src/github.com/ibm/ibm-block-csi-driver
ENV GO111MODULE=on

# Populate the module cache based on the go.{mod,sum} files.
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go get github.com/tebeka/go2xunit   # when GO111MODULE=on the module will not become executable, so get it here to run it as binary.
RUN go get github.com/golang/mock/gomock
RUN go install github.com/golang/mock/mockgen

COPY . .
ENTRYPOINT ["make", "test-xunit"]
