# Copyright IBM Corporation 2026.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Description:
#    This Dockerfile.test is for running the csi controller local tests inside a container.
#    Its similar to the Dockerfile, but with additional requirements-tests.txt and ENTRYPOINT to run the local tests.

FROM registry.access.redhat.com/ubi9/python-312:1-1788919789 AS builder
USER root
RUN if [[ "$(uname -m)" != "x86"* ]]; then yum install -y rust-toolset; fi

USER default
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /tmp
COPY controllers/servers/csi/requirements.txt ./csi_requirements.txt
COPY controllers/servers/csi/requirements_pyxcli.txt ./csi_requirements_pyxcli.txt
COPY controllers/servers/host_definer/requirements.txt ./host_definer_requirements.txt
# avoid default- boringssl lib, since it does not support z systems
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True
RUN pip3 install -r ./csi_requirements.txt -r ./host_definer_requirements.txt
# s390x: replace the native UPB wheel with the pure-Python universal wheel to avoid
# a SIGSEGV in _message.abi3.so at Python interpreter shutdown (issue #870)
RUN if [ "$(uname -m)" = "s390x" ]; then \
        pip3 install "protobuf==6.33.5" --no-binary protobuf ; \
    fi
RUN pip3 install --no-deps -r ./csi_requirements_pyxcli.txt

USER root
COPY controllers/scripts/csi_general .
RUN chmod +x csi_pb2.sh
RUN ./csi_pb2.sh
RUN pip3 install .

# Requires to run local testing
COPY controllers/tests/requirements.txt ./requirements-tests.txt
RUN pip3 install -r ./requirements-tests.txt

FROM registry.access.redhat.com/ubi9/python-312:1-1788919789

COPY --from=builder /opt/app-root /opt/app-root
COPY ./common /driver/common
COPY ./controllers/ /driver/controllers/

USER root
RUN groupadd -g 9999 appuser && \
    useradd -r -u 9999 -g appuser appuser

RUN chown -R appuser:appuser /driver /opt/app-root

USER appuser
WORKDIR /driver

ENV PYTHONPATH=/driver
# s390x: force pure-Python protobuf backend; belt-and-suspenders alongside wheel swap in builder
# (replaces the previous no-op "export" inside RUN which had no effect)
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

ENTRYPOINT ["/driver/controllers/scripts/entrypoint-test.sh"]
