FROM registry.access.redhat.com/ubi9/python-39:1-1775726797 AS builder

USER root
RUN if [[ "$(uname -m)" != "x86"* ]]; then yum install -y rust-toolset gcc python3-devel; fi

USER default
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
WORKDIR /tmp
COPY controllers/servers/csi/requirements.txt ./csi_requirements.txt
COPY controllers/servers/host_definer/requirements.txt ./host_definer_requirements.txt
# avoid default- boringssl lib, since it does not support z systems
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True
# Use pre-built wheels when available to speed up build on non-x86 platforms
ENV PIP_PREFER_BINARY=1
RUN pip3 install --timeout=300 --retries=5 -r ./csi_requirements.txt -r ./host_definer_requirements.txt

USER root
COPY controllers/scripts/csi_general .
RUN chmod +x csi_pb2.sh
RUN ./csi_pb2.sh
RUN pip3 install .

FROM registry.access.redhat.com/ubi9/python-39:1-1775726797

ARG VERSION=1.14.0
ARG BUILD_NUMBER=0

###Required Labels
LABEL name="IBM block storage CSI driver host definer" \
      vendor="IBM" \
      maintainer="IBM" \
      version=$VERSION \
      release=$BUILD_NUMBER \
      summary="The host definer defines Kubernetes nodes on IBM block storage" \
      description="The host definer defines container orchestrator nodes on IBM block storage." \
      io.k8s.display-name="IBM block storage CSI driver host definer" \
      io.k8s.description="The host definer defines container orchestrator nodes on IBM block storage." \
      io.openshift.tags=ibm,csi,ibm-block-csi-driver,host-definer

COPY --from=builder /opt/app-root /opt/app-root
COPY ./common /driver/common
COPY ./controllers/ /driver/controllers/
COPY ./LICENSE /licenses/

WORKDIR /driver/controllers/servers/host_definer/
ENV PYTHONPATH=/driver

USER default
CMD ["python3", "/driver/controllers/servers/host_definer/main.py"]
