# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.11

COPY node /node
COPY scripts/csi_node_code_scan_entrypoint.sh entrypoint.sh
RUN mkdir /results

RUN groupadd -g 9999 appuser && \
    useradd -r -u 9999 -g appuser appuser
RUN chown -R appuser:appuser /node /results entrypoint.sh
RUN go get github.com/securego/gosec/cmd/gosec


USER appuser
WORKDIR .

ENTRYPOINT ["./entrypoint.sh"]

