# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.11
#RUN yum --enablerepo=extras -y install epel-release && yum -y install python2-pip

RUN git clone https://github.com/kubernetes-csi/csi-test /csi-test
#RUN make -C /csi-test

COPY ./scripts/csi_test /csi-test/ibm-driver

RUN cat test_to_run | paste -sd "|"

RUN groupadd -g 9999 appuser && \
    useradd -r -u 9999 -g appuser appuser
RUN chown -R appuser:appuser /csi-test
USER appuser
WORKDIR /csi-test

ENTRYPOINT ["/csi-test/ibm-driver/run_csi_test.sh", "/tmp/b", "/csi-test/ibm-driver/olga_secrets", "/csi-test/ibm-driver/olga_params", `cat ../../IBM/ibm-block-csi-driver/scripts/csi_test/test_to_run | paste -sd "|"` ]


