# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Description:
#    This Dockerfile.test is for running the csi controller local tests inside a container.
#    Its similar to the Dockerfile, but with additional requirements-tests.txt and ENTRYPOINT to run the local tests.

FROM registry.access.redhat.com/ubi7/python-36:1-58

COPY controller/requirements.txt /driver/controller/
RUN pip3 install --upgrade pip==19.1.1
# avoid default boringssl lib, since it does not support z systems
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True
RUN pip3 install -r /driver/controller/requirements.txt

# Requires to run local testing
COPY controller/requirements-tests.txt /driver/controller/
RUN pip3 install -r /driver/controller/requirements-tests.txt

COPY ./common /driver/common
COPY ./controller /driver/controller
USER root
RUN groupadd -g 9999 appuser && \
    useradd -r -u 9999 -g appuser appuser
RUN chown -R appuser:appuser /driver /opt/app-root
USER appuser
WORKDIR /driver

ENTRYPOINT ["/driver/controller/scripts/entrypoint-test.sh"]
