FROM registry.access.redhat.com/ubi9/python-312:1-1778473732 AS builder

USER root
RUN if [[ "$(uname -m)" != "x86"* ]]; then yum install -y rust-toolset; fi

USER default
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
RUN if [[ "$(uname -m)" == "s390x" ]]; then \
    export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python; \
    fi

WORKDIR /tmp
COPY controllers/servers/csi/requirements.txt ./csi_requirements.txt
COPY controllers/servers/csi/requirements_pyxcli.txt ./csi_requirements_pyxcli.txt
COPY controllers/servers/host_definer/requirements.txt ./host_definer_requirements.txt
# avoid default- boringssl lib, since it does not support z systems
ENV GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True
COPY --from=quay.io/sushilmaxbhile/csi-deps:v2 /wheels /wheels
RUN pip3 install --no-index --find-links=/wheels -r ./csi_requirements.txt -r ./host_definer_requirements.txt
RUN pip3 install --no-deps -r ./csi_requirements_pyxcli.txt

USER root
COPY controllers/scripts/csi_general .
RUN chmod +x csi_pb2.sh
RUN ./csi_pb2.sh
RUN pip3 install .

FROM registry.access.redhat.com/ubi9/python-312:1-1778473732

ARG VERSION=1.14.0
ARG BUILD_NUMBER=0

###Required Labels
LABEL name="IBM block storage CSI driver host definer" \
      vendor="IBM" \
      maintainer="IBM" \
      version=$VERSION \
      release=$BUILD_NUMBER \
      summary="The host definer defines Kubernetes nodes on IBM block storage" \
      description="The host definer defines container orchestrator nodes on IBM block storage." \
      io.k8s.display-name="IBM block storage CSI driver host definer" \
      io.k8s.description="The host definer defines container orchestrator nodes on IBM block storage." \
      io.openshift.tags=ibm,csi,ibm-block-csi-driver,host-definer

RUN if [[ "$(uname -m)" == "s390x" ]]; then \
    export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python; \
    fi

COPY --from=builder /opt/app-root /opt/app-root
COPY ./common /driver/common
COPY ./controllers/ /driver/controllers/
COPY ./LICENSE /licenses/

WORKDIR /driver/controllers/servers/host_definer/
ENV PYTHONPATH=/driver

USER default
ENTRYPOINT ["/driver/controllers/scripts/entrypoint-hostdefiner.sh"]
