# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM registry.access.redhat.com/ubi8/python-36:1
MAINTAINER IBM Systems Engineering <TBD>

###Required Labels
LABEL name="CSI controller for IBM Block CSI Driver"
LABEL vendor="IBM"
LABEL version="1.0.0"
# TODO inject release automatically
LABEL release="b1" 
LABEL summary="The CSI controller component of the IBM block storage CSI driver"
LABEL description="The IBM block storage CSI driver enables container orchestrators, such as Kubernetes and Openshift, to manage the life-cycle of persistent storage."
LABEL io.k8s.display-name="CSI node for IBM Block CSI Driver"
LABEL io.k8s.description="The IBM block storage CSI driver enables container orchestrators, such as Kubernetes and Openshift, to manage the life-cycle of persistent storage."
LABEL io.openshift.tags=ibm,csi,ibm-block-csi-driver,ibm-block-csi-node

COPY controller/requirements.txt /driver/controller/
RUN pip3 install --upgrade pip==19.1.1
RUN pip3 install -r /driver/controller/requirements.txt

COPY ./common /driver/common
COPY ./controller /driver/controller
#COPY ./image_license /licenses   # TODO need to add relevant license before GA
WORKDIR /driver
ENV PYTHONPATH=/driver

# Note, UBI runs with app-user by default.

ENTRYPOINT ["/driver/controller/scripts/entrypoint.sh"]


