# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.11
#RUN yum --enablerepo=extras -y install epel-release && yum -y install python2-pip

RUN git clone https://github.com/kubernetes-csi/csi-test /usr/local/go/src/github.com/kubernetes-csi/csi-test
RUN make -C /usr/local/go/src/github.com/kubernetes-csi/csi-test

COPY ./scripts/csi_test /usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver

RUN groupadd -g 9999 appuser && \
    useradd -r -u 9999 -g appuser appuser
RUN chown -R appuser:appuser /usr/local/go/src/github.com/kubernetes-csi/csi-test
RUN touch /tmp/b
RUN chown -R appuser:appuser /tmp/b
USER appuser
WORKDIR /usr/local/go/src/github.com/kubernetes-csi/csi-test

ARG MGMT_ADDRESS
ARG USERNAME
ARG PASSWORD
ARG TESTS_TO_RUN

ENV MGMT_ADDRESS $MGMT_ADDRESS
ENV USERNAME $USERNAME
ENV PASSWORD $PASSWORD
ENV TESTS_TO_RUN $TESTS_TO_RUN

RUN echo $TESTS_TO_RUN 

ENTRYPOINT ["/usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver/entrypoint-csi-sanity.sh", "/tmp/k8s_dir/f", "/usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver/csi_secrets", "/usr/local/go/src/github.com/kubernetes-csi/csi-test/ibm-driver/csi_params", "/tmp/test_results/out_client.xml"]

