# Copyright IBM Corporation 2019.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Build stage
FROM golang:1.12.6 as builder

WORKDIR /go/src/github.com/ibm/ibm-block-csi-driver
ENV GO111MODULE=on

COPY node ./node
RUN mkdir /results
RUN go get github.com/securego/gosec/cmd/gosec

ENTRYPOINT ["/bin/sh", "-c", "/go/bin/gosec -fmt=json -no-fail ./... > /results/${TARGET_NAME}.json 2> /results/${TARGET_NAME}.log"]
