ID_KEY = "id"
NAME_KEY = "name"

DUMMY_USER_PARAMETER = "user"
DUMMY_PASSWORD_PARAMETER = "password"

NVME_OVER_FC_CONNECTIVITY_TYPE = "nvmeofc"
FC_CONNECTIVITY_TYPE = "fc"
ISCSI_CONNECTIVITY_TYPE = "iscsi"
DUMMY_CONNECTIVITY_TYPE = "connectivity_type"
DUMMY_ERROR_MESSAGE = "failed"

DUMMY_HOST_NAME1 = "host_name_1"
DUMMY_HOST_NAME2 = "host_name_2"
DUMMY_HOST_NAME3 = "host_name_3"

DUMMY_HOST_ID1 = "host_id_1"
DUMMY_HOST_ID2 = "host_id_2"
DUMMY_HOST_ID3 = "host_id_3"
DUMMY_HOST_ID4 = "host_id_4"

DUMMY_NODE1_NAME = "node1"
DUMMY_NODE2_NAME = "node2"

DUMMY_NODE1_IQN = "iqn.test.node1"
DUMMY_NODE2_IQN = "iqn.test.node2"
DUMMY_NODE3_IQN = "iqn.test.node3"
DUMMY_NODE4_IQN = "iqn.test.node4"
DUMMY_NODE5_IQN = "iqn.test.node5"

DUMMY_FC_WWN1 = "wwn1"
DUMMY_FC_WWN2 = "wwn2"
DUMMY_FC_WWN3 = "wwn3"
DUMMY_FC_WWN4 = "wwn4"
DUMMY_FC_WWN5 = "wwn5"

DUMMY_NVME_NQN1 = "nqn.test.s1"
DUMMY_NVME_NQN2 = "nqn.test.s2"
DUMMY_NVME_NQN3 = "nqn.test.s3"
DUMMY_NVME_NQN4 = "nqn.test.s4"

VOLUME_ID_ATTR_KEY = ID_KEY
VOLUME_NAME_ATTR_KEY = NAME_KEY

DUMMY_LUN_ID = "5"
DUMMY_LUN_ID_INT = 5

DUMMY_CAPACITY_STR = "1024"
DUMMY_SMALL_CAPACITY_STR = "512"
DUMMY_CAPACITY_INT = 1024
DUMMY_SMALL_CAPACITY_INT = 512

DUMMY_IP_ADDRESS1 = "1.1.1.1"
DUMMY_IP_ADDRESS2 = "2.2.2.2"
DUMMY_IP_ADDRESS_6_1 = "1::1"
