from controllers.common.config import config

NAME_PREFIX_SEPARATOR = "_"
ENDPOINTS_SEPARATOR = ", "

CSI_CONTROLLER_SERVER_WORKERS = 10

# array types
ARRAY_TYPE_XIV = 'A9000'
ARRAY_TYPE_SVC = 'SVC'
ARRAY_TYPE_DS8K = 'DS8K'
ALL_ARRAY_TYPES = [ARRAY_TYPE_XIV, ARRAY_TYPE_SVC, ARRAY_TYPE_DS8K]

PARAMETERS_NODE_ID_DELIMITER = config.parameters.node_id_info.delimiter
