# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from controller.csi_general import replication_pb2 as controller_dot_csi__general_dot_replication__pb2


class ControllerStub(object):
  """Controller holds the RPC Methods for replication and all the methods it
  exposes should be idempotent.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.EnableVolumeReplication = channel.unary_unary(
        '/replication.Controller/EnableVolumeReplication',
        request_serializer=controller_dot_csi__general_dot_replication__pb2.EnableVolumeReplicationRequest.SerializeToString,
        response_deserializer=controller_dot_csi__general_dot_replication__pb2.EnableVolumeReplicationResponse.FromString,
        )
    self.DisableVolumeReplication = channel.unary_unary(
        '/replication.Controller/DisableVolumeReplication',
        request_serializer=controller_dot_csi__general_dot_replication__pb2.DisableVolumeReplicationRequest.SerializeToString,
        response_deserializer=controller_dot_csi__general_dot_replication__pb2.DisableVolumeReplicationResponse.FromString,
        )
    self.PromoteVolume = channel.unary_unary(
        '/replication.Controller/PromoteVolume',
        request_serializer=controller_dot_csi__general_dot_replication__pb2.PromoteVolumeRequest.SerializeToString,
        response_deserializer=controller_dot_csi__general_dot_replication__pb2.PromoteVolumeResponse.FromString,
        )
    self.DemoteVolume = channel.unary_unary(
        '/replication.Controller/DemoteVolume',
        request_serializer=controller_dot_csi__general_dot_replication__pb2.DemoteVolumeRequest.SerializeToString,
        response_deserializer=controller_dot_csi__general_dot_replication__pb2.DemoteVolumeResponse.FromString,
        )
    self.ResyncVolume = channel.unary_unary(
        '/replication.Controller/ResyncVolume',
        request_serializer=controller_dot_csi__general_dot_replication__pb2.ResyncVolumeRequest.SerializeToString,
        response_deserializer=controller_dot_csi__general_dot_replication__pb2.ResyncVolumeResponse.FromString,
        )


class ControllerServicer(object):
  """Controller holds the RPC Methods for replication and all the methods it
  exposes should be idempotent.
  """

  def EnableVolumeReplication(self, request, context):
    """EnableVolumeReplication RPC call to enable the volume replication.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisableVolumeReplication(self, request, context):
    """DisableVolumeReplication RPC call to disable the volume replication.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PromoteVolume(self, request, context):
    """PromoteVolume RPC call to promote the volume.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DemoteVolume(self, request, context):
    """DemoteVolume RPC call to demote the volume.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResyncVolume(self, request, context):
    """ResyncVolume RPC call to resync the volume.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'EnableVolumeReplication': grpc.unary_unary_rpc_method_handler(
          servicer.EnableVolumeReplication,
          request_deserializer=controller_dot_csi__general_dot_replication__pb2.EnableVolumeReplicationRequest.FromString,
          response_serializer=controller_dot_csi__general_dot_replication__pb2.EnableVolumeReplicationResponse.SerializeToString,
      ),
      'DisableVolumeReplication': grpc.unary_unary_rpc_method_handler(
          servicer.DisableVolumeReplication,
          request_deserializer=controller_dot_csi__general_dot_replication__pb2.DisableVolumeReplicationRequest.FromString,
          response_serializer=controller_dot_csi__general_dot_replication__pb2.DisableVolumeReplicationResponse.SerializeToString,
      ),
      'PromoteVolume': grpc.unary_unary_rpc_method_handler(
          servicer.PromoteVolume,
          request_deserializer=controller_dot_csi__general_dot_replication__pb2.PromoteVolumeRequest.FromString,
          response_serializer=controller_dot_csi__general_dot_replication__pb2.PromoteVolumeResponse.SerializeToString,
      ),
      'DemoteVolume': grpc.unary_unary_rpc_method_handler(
          servicer.DemoteVolume,
          request_deserializer=controller_dot_csi__general_dot_replication__pb2.DemoteVolumeRequest.FromString,
          response_serializer=controller_dot_csi__general_dot_replication__pb2.DemoteVolumeResponse.SerializeToString,
      ),
      'ResyncVolume': grpc.unary_unary_rpc_method_handler(
          servicer.ResyncVolume,
          request_deserializer=controller_dot_csi__general_dot_replication__pb2.ResyncVolumeRequest.FromString,
          response_serializer=controller_dot_csi__general_dot_replication__pb2.ResyncVolumeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'replication.Controller', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
