ISCSI_CONNECTIVITY_TYPE = "iscsi"
FC_CONNECTIVITY_TYPE = "fc"
SPACE_EFFICIENCY_THIN = 'thin'
SPACE_EFFICIENCY_COMPRESSED = 'compressed'
SPACE_EFFICIENCY_DEDUPLICATED = 'deduplicated'
SPACE_EFFICIENCY_THICK = 'thick'
SPACE_EFFICIENCY_NONE = 'none'

# volume context
CONTEXT_POOL = "pool"
