NVME_OVER_FC_CONNECTIVITY_TYPE = "nvmeofc"
FC_CONNECTIVITY_TYPE = "fc"
ISCSI_CONNECTIVITY_TYPE = "iscsi"
SPACE_EFFICIENCY_THIN = "thin"
SPACE_EFFICIENCY_COMPRESSED = "compressed"
SPACE_EFFICIENCY_DEDUPLICATED = "deduplicated"
SPACE_EFFICIENCY_DEDUPLICATED_THIN = "dedup_thin"
SPACE_EFFICIENCY_DEDUPLICATED_COMPRESSED = "dedup_compressed"
SPACE_EFFICIENCY_THICK = "thick"
SPACE_EFFICIENCY_NONE = "none"
REPLICATION_COPY_TYPE_SYNC = "sync"
REPLICATION_COPY_TYPE_ASYNC = "async"
REPLICATION_DEFAULT_COPY_TYPE = REPLICATION_COPY_TYPE_SYNC

# volume context
CONTEXT_POOL = "pool"

WWN_OUI_END = 7
WWN_VENDOR_IDENTIFIER_END = 16

LPFC_MAX_LUNS = 255
