ISCSI_CONNECTIVITY_TYPE = "iscsi"
FC_CONNECTIVITY_TYPE = "fc"
CAPABILITIES_SPACEEFFICIENCY = 'SpaceEfficiency'
CAPABILITY_THIN = 'thin'
CAPABILITY_COMPRESSED = 'compressed'
CAPABILITY_DEDUPLICATED = 'deduplicated'
CAPABILITY_THICK = 'thick'

# volume context
CONTEXT_POOL = "pool"
