from controllers.tests.array_action.test_settings import ID_KEY, NAME_KEY

VOLUME_FAKE_NAME = "volume_fake_name"
UNSUPPORTED_SPACE_EFFICIENCY = "fake"

CAP_KEY = "cap"
STATE_KEY = "state"

PYDS8K_REPRESENTATION_KEY = "representation"
DS8K_SPACE_EFFICIENCY_THIN = "ese"

VOLUME_CAPACITY_ATTR_KEY = CAP_KEY
VOLUME_POOL_ID_ATTR_KEY = "pool"
VOLUME_SE_ATTR_KEY = "tp"
VOLUME_FLASHCOPY_ATTR_KEY = "flashcopy"

DUMMY_VOLUME_ID1 = "0001"
DUMMY_VOLUME_ID2 = "0002"
DUMMY_VOLUME_ID3 = "0003"
DUMMY_VOLUME_UID = "volume_scsi_id_0001"
DUMMY_ABSTRACT_VOLUME_UID = "volume_scsi_id_{}"
DUMMY_VOLUME_CAPACITY = "1073741824"

FLASHCOPY_SOURCE_VOLUME_ATTR_KEY = "sourcevolume"
FLASHCOPY_TARGET_VOLUME_ATTR_KEY = "targetvolume"
FLASHCOPY_STATE_ATTR_KEY = STATE_KEY
FLASHCOPY_ID_ATTR_KEY = ID_KEY
FLASHCOPY_BACKGROUND_COPY_ATTR_KEY = "backgroundcopy"
FLASHCOPY_OUT_OF_SYNC_TRACKS_ATTR_KEY = "out_of_sync_tracks"
FLASHCOPY_ID_DELIMITER = ":"

DUMMY_OUT_OF_SYNC_TRACKS = "55"
DUMMY_ZERO_OUT_OF_SYNC_TRACKS = "0"

GET_SYSTEM_ID_ATTR_KEY = ID_KEY
GET_SYSTEM_BUNDLE_ATTR_KEY = "bundle"
GET_SYSTEM_WWNN_ATTR_KEY = "wwnn"
DUMMY_GET_SYSTEM_ID = "dsk array id"
DUMMY_SYSTEM_BUNDLE = "87.51.47.0"
DUMMY_UNSUPPORTED_SYSTEM_BUNDLE = "87.50.34.0"
DUMMY_SYSTEM_WWNN = "5005076306FFD2F0"

VALID_STATE = "valid"
INVALID_STATE = "invalid"
ENABLED_BACKGROUND_COPY = "enabled"
DISABLED_BACKGROUND_COPY = "disabled"

GET_HOSTS_MAPPINGS_BRIEFS_ATTR_KEY = "mappings_briefs"
GET_HOSTS_VOLUME_ID_ATTR_KEY = "volume_id"
GET_HOSTS_LUN_ID_ATTR_KEY = "lunid"
GET_HOSTS_NAME_ATTR_KEY = NAME_KEY
GET_HOST_LOGIN_PORTS_ATTR_KEY = "login_ports"
GET_HOSTS_HOST_PORTS_BRIEFS_ATTR_KEY = "host_ports_briefs"
GET_HOSTS_WWPN_ATTR_KEY = "wwpn"

LOGIN_PORT_STATE_OFFLINE = "offline"

GET_HOST_MAPPINGS_VOLUME_ATTR_KEY = "volume"
GET_HOST_MAPPINGS_ID_ATTR_KEY = ID_KEY
