from controllers.common.settings import TOPOLOGY_IBM_BLOCK_PREFIX, STORAGE_API_GROUP
import controllers.array_action.settings as array_config

STORAGE_API_VERSION = '{}/v1'.format(STORAGE_API_GROUP)
CSINODE_KIND = 'CSINode'
PENDING_PREFIX = 'Pending'
SUPPORTED_CONNECTIVITY_TYPES = [array_config.ISCSI_CONNECTIVITY_TYPE,
                                array_config.FC_CONNECTIVITY_TYPE, array_config.NVME_OVER_FC_CONNECTIVITY_TYPE]
SUCCESS_MESSAGE = 'Host defined successfully on the array'
HOST_DEFINITION_PENDING_RETRIES = 5
HOST_DEFINITION_PENDING_EXPONENTIAL_BACKOFF_IN_SECONDS = 3
HOST_DEFINITION_PENDING_DELAY_IN_SECONDS = 3
TOPOLOGY_PREFIXES = [TOPOLOGY_IBM_BLOCK_PREFIX]
POSSIBLE_NUMBER_OF_IO_GROUP = 4
