apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: demo-snapshot
spec:
  volumeSsnapshotClassName: demo-snapshotclass
  source:
    persistentVolumeClaimName: demo-pvc-file-system
