kind: Secret
apiVersion: v1
metadata:
  name:  demo-secret
  namespace: default
type: Opaque
stringData:
  management_address: demo-management-address  # Array management addresses
  username: demo-username                      # Array username
data:
  password: ZGVtby1wYXNzd29yZA==               # base64 array password
