apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: demo-snapshotclass
driver: block.csi.ibm.com
deletionPolicy: Delete
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: demo-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: default
  snapshot_name_prefix: demoSnapshot   # Optional.
  pool: demo-pool                      # Optional. Use to create the snapshot on a different pool than the source.
