apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: <VALUE_SNAPSHOT_NAME>
spec:
  snapshotClassName: <VALUE_SNAPSHOT_CLASS_NAME>
  source:
    name: <VALUE_PVC_NAME>
    kind: PersistentVolumeClaim
